[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "N", "S", "W", "C90"]
ignore = ["E203", "E266", "E501"]  # handled by Black / common false positives

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]


[tool.mypy]
python_version = "3.10"
strict = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true  # relax until deps are pinned

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
