services:
  airflow:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__WEBSERVER__SECRET_KEY: "please-change-this-to-a-long-random-string"
      PYTHONPATH: "/opt/airflow/src"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
      - ../logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >-
      bash -lc "pip install --no-cache-dir pandas pyarrow transformers torch &&
                airflow db init &&
                airflow webserver & airflow scheduler"
