name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.api.txt
          pip install -r requirements-dev.txt || true

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run pytest
        run: pytest -q

      - name: Build API Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/api.Dockerfile
          push: false
          tags: moderation-api:ci
